name: Deploy Application

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: Test_vautra

    steps:
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io \
            -u P70750 \
            --password-stdin

      - name: Pull Latest Image
        run: |
          docker pull ghcr.io/p70750/test_vautra:latest

      - name: Stop Existing Container
        run: |
          docker stop test_vautra || true

      - name: Remove Existing Container
        run: |
          docker rm test_vautra || true

      - name: Run Container
        run: |
          docker run -d \
            --name test_vautra \
            -p 8090:80 \
            --restart always \
            ghcr.io/p70750/test_vautra:latest
